// AUTH
export const AUTH_LOADING = "AUTH_LOADING"
export const AUTH_SUCCESS = "AUTH_SUCCESS"
export const AUTH_FAILED = "AUTH_FAILED"
// SELL
export const SELL_LIST_LOADING = "SELL_LIST_LOADING"
export const SELL_LIST_SUCCESS = "SELL_LIST_SUCCESS"
export const SELL_LIST_FAILED = "SELL_LIST_FAILED"
export const SELL_LIST_RESET = "SELL_LIST_RESET"